# Generated by Django 4.2 on 2024-08-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_tagarticle_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagarticle',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
