# Generated by Django 4.2 on 2024-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_tagarticle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagarticle',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True),
        ),
    ]
