# Generated by Django 4.2 on 2024-08-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_tagarticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagarticle',
            name='slug',
            field=models.SlugField(auto_created=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='tagarticle',
            name='tag',
            field=models.CharField(max_length=50, verbose_name='Тег'),
        ),
    ]
